In [1]:
import pandas as pd
import io
from kbb import Cars
import time

In [2]:
carapi = pd.read_csv("carapi-opendatafeed-sample.csv")
carapi

,Make Id,Make Name,Model Id,Model Name,Trim Id,Trim Year,Trim Name,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Epa Highway Mpg,Mileage Range City,Mileage Range Highway,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric
0,1,Acura,97,ILX,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Acura,97,ILX,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Acura,97,ILX,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Acura,97,ILX,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Acura,97,ILX,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,Volvo,589,XC70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,25.0,3330.0,4625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17658,23,Volvo,589,XC70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,31.0,4440.0,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17659,23,Volvo,589,XC70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,31.0,4440.0,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17660,23,Volvo,589,XC70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,24.0,3145.0,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17661,23,Volvo,589,XC70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,24.0,3145.0,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
unique_cars = carapi[["Make Name", "Model Name", "Trim Year"]].drop_duplicates()
unique_cars

      Make Name         Model Name  Trim Year
0         Acura                ILX       2020
5         Acura                MDX       2020
17        Acura                NSX       2020
18        Acura                RDX       2020
26        Acura                RLX       2020
...         ...                ...        ...
17611     Volvo                S80       2015
17615     Volvo                V60       2015
17621     Volvo  V60 Cross Country       2015
17623     Volvo               XC60       2015
17656     Volvo               XC70       2015

[2183 rows x 3 columns]

In [4]:
car_prices = []
for index, row in unique_cars.iterrows():
    car = Cars(row['Make Name'].lower(), row['Model Name'].lower(), row['Trim Year'])
    car_prices.append(car.get_prices())
    #time.sleep()

'NoneType' object has no attribute 'find'
audi
tt rs
2020
'NoneType' object has no attribute 'find'
audi
tts
2020
'NoneType' object has no attribute 'find'
bmw
2 series gran coupe
2020
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2020
'NoneType' object has no attribute 'find'
bmw
8 series gran coupe
2020
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2020
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2020
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2020
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2020
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2020
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2020
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2020
'NoneType' object has no attribute 'find'
ford
shelby gt350
2020
'NoneType' object has no attribute 'find'
ford
shelby gt500
2020
'NoneType' object has no attribute 'find'
ford
transit cargo van
2020
'NoneType' object has no attribute 'find'
ford
transit crew van
2020
'NoneType' object has no attribute 'find'
ford
transit passenger van
2020
'NoneType' object has no attribute 'find'
gmc
savana cargo
2020
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2020
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2020
'NoneType' object has no attribute 'find'
honda
clarity
2020
'NoneType' object has no attribute 'find'
land rover
defender
2020
'NoneType' object has no attribute 'find'
mazda
3
2020
'NoneType' object has no attribute 'find'
mazda
6
2020
'NoneType' object has no attribute 'find'
mclaren
570s spider
2020
'NoneType' object has no attribute 'find'
mclaren
600lt spider
2020
'NoneType' object has no attribute 'find'
mclaren
720s spider
2020
'NoneType' object has no attribute 'find'
mercedes-benz
amg gt
2020
'NoneType' object has no attribute 'find'
mercedes-benz
cla-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
gla-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
glb-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class coupe
2020
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
gls-class
2020
'NoneType' object has no attribute 'find'
mercedes-benz
maybach
2020
'NoneType' object has no attribute 'find'
mercedes-benz
slc-class
2020
'NoneType' object has no attribute 'find'
nissan
nv cargo
2020
'NoneType' object has no attribute 'find'
nissan
nv passenger
2020
'NoneType' object has no attribute 'find'
ram
1500
2020
'NoneType' object has no attribute 'find'
ram
1500 classic
2020
'NoneType' object has no attribute 'find'
ram
2500
2020
'NoneType' object has no attribute 'find'
ram
3500
2020
'NoneType' object has no attribute 'find'
volvo
v60 cross country
2020
'NoneType' object has no attribute 'find'
volvo
v90 cross country
2020
'NoneType' object has no attribute 'find'
aston martin
rapide amr
2019
'NoneType' object has no attribute 'find'
audi
tt rs
2019
'NoneType' object has no attribute 'find'
audi
tts
2019
'NoneType' object has no attribute 'find'
bmw
3 series gran turismo
2019
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2019
'NoneType' object has no attribute 'find'
bmw
6 series gran coupe
2019
'NoneType' object has no attribute 'find'
bmw
6 series gran turismo
2019
'NoneType' object has no attribute 'find'
bmw
alpina b6 gran coupe
2019
'NoneType' object has no attribute 'find'
cadillac
ats coupe
2019
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2019
'NoneType' object has no attribute 'find'
chevrolet
silverado 1500 ld
2019
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2019
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2019
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2019
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2019
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2019
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2019
'NoneType' object has no attribute 'find'
ford
shelby gt350
2019
'NoneType' object has no attribute 'find'
ford
transit passenger van
2019
'NoneType' object has no attribute 'find'
ford
transit van
2019
'NoneType' object has no attribute 'find'
gmc
savana cargo
2019
'NoneType' object has no attribute 'find'
gmc
sierra 1500 limited
2019
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2019
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2019
'NoneType' object has no attribute 'find'
honda
clarity
2019
'NoneType' object has no attribute 'find'
jaguar
xj-series
2019
'NoneType' object has no attribute 'find'
maserati
granturismo convertible
2019
'NoneType' object has no attribute 'find'
mazda
3
2019
'NoneType' object has no attribute 'find'
mazda
6
2019
'NoneType' object has no attribute 'find'
mclaren
570s spider
2019
'NoneType' object has no attribute 'find'
mclaren
720s spider
2019
'NoneType' object has no attribute 'find'
mclaren
senna
2019
'NoneType' object has no attribute 'find'
mercedes-benz
amg gt
2019
'NoneType' object has no attribute 'find'
mercedes-benz
cla-class
2019
'NoneType' object has no attribute 'find'
mercedes-benz
gla-class
2019
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class
2019
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class coupe
2019
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class
2019
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class coupe
2019
'NoneType' object has no attribute 'find'
mercedes-benz
gls-class
2019
'NoneType' object has no attribute 'find'
mercedes-benz
maybach
2019
'NoneType' object has no attribute 'find'
mercedes-benz
slc-class
2019
'NoneType' object has no attribute 'find'
nissan
nv cargo
2019
'NoneType' object has no attribute 'find'
nissan
nv passenger
2019
'NoneType' object has no attribute 'find'
ram
1500
2019
'NoneType' object has no attribute 'find'
ram
1500 classic
2019
'NoneType' object has no attribute 'find'
ram
2500
2019
'NoneType' object has no attribute 'find'
ram
3500
2019
'NoneType' object has no attribute 'find'
smart
eq fortwo
2019
'NoneType' object has no attribute 'find'
volkswagen
beetle convertible
2019
'NoneType' object has no attribute 'find'
volvo
v90 cross country
2019
'NoneType' object has no attribute 'find'
audi
tt rs
2018
'NoneType' object has no attribute 'find'
audi
tts
2018
'NoneType' object has no attribute 'find'
bmw
3 series gran turismo
2018
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2018
'NoneType' object has no attribute 'find'
bmw
6 series gran coupe
2018
'NoneType' object has no attribute 'find'
bmw
6 series gran turismo
2018
'NoneType' object has no attribute 'find'
bmw
alpina b6 gran coupe
2018
'NoneType' object has no attribute 'find'
cadillac
ats coupe
2018
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2018
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2018
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2018
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2018
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2018
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2018
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2018
'NoneType' object has no attribute 'find'
ford
shelby gt350
2018
'NoneType' object has no attribute 'find'
ford
transit van
2018
'NoneType' object has no attribute 'find'
ford
transit wagon
2018
'NoneType' object has no attribute 'find'
gmc
savana cargo
2018
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2018
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2018
'NoneType' object has no attribute 'find'
honda
clarity
2018
'NoneType' object has no attribute 'find'
jaguar
xj-series
2018
'NoneType' object has no attribute 'find'
jeep
wrangler jk
2018
'NoneType' object has no attribute 'find'
maserati
granturismo convertible
2018
'NoneType' object has no attribute 'find'
mazda
3
2018
'NoneType' object has no attribute 'find'
mazda
6
2018
'NoneType' object has no attribute 'find'
mclaren
570s spider
2018
'NoneType' object has no attribute 'find'
mercedes-benz
amg gt
2018
'NoneType' object has no attribute 'find'
mercedes-benz
cla-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
gla-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class coupe
2018
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class coupe
2018
'NoneType' object has no attribute 'find'
mercedes-benz
gls-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
maybach
2018
'NoneType' object has no attribute 'find'
mercedes-benz
slc-class
2018
'NoneType' object has no attribute 'find'
mercedes-benz
sprinter worker
2018
'NoneType' object has no attribute 'find'
nissan
nv cargo
2018
'NoneType' object has no attribute 'find'
nissan
nv passenger
2018
'NoneType' object has no attribute 'find'
ram
1500
2018
'NoneType' object has no attribute 'find'
ram
2500
2018
'NoneType' object has no attribute 'find'
ram
3500
2018
'NoneType' object has no attribute 'find'
volkswagen
beetle convertible
2018
'NoneType' object has no attribute 'find'
volvo
s60 cross country
2018
'NoneType' object has no attribute 'find'
volvo
v60 cross country
2018
'NoneType' object has no attribute 'find'
volvo
v90 cross country
2018
'NoneType' object has no attribute 'find'
aston martin
rapide s
2017
'NoneType' object has no attribute 'find'
aston martin
v12 vantage s
2017
'NoneType' object has no attribute 'find'
audi
tts
2017
'NoneType' object has no attribute 'find'
bmw
3 series gran turismo
2017
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2017
'NoneType' object has no attribute 'find'
bmw
5 series gran turismo
2017
'NoneType' object has no attribute 'find'
bmw
6 series gran coupe
2017
'NoneType' object has no attribute 'find'
bmw
alpina b6 gran coupe
2017
'NoneType' object has no attribute 'find'
cadillac
ats coupe
2017
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2017
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2017
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2017
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2017
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2017
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2017
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2017
'NoneType' object has no attribute 'find'
ford
shelby gt350
2017
'NoneType' object has no attribute 'find'
ford
transit van
2017
'NoneType' object has no attribute 'find'
ford
transit wagon
2017
'NoneType' object has no attribute 'find'
gmc
savana cargo
2017
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2017
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2017
'NoneType' object has no attribute 'find'
honda
clarity
2017
'NoneType' object has no attribute 'find'
jaguar
xj-series
2017
'NoneType' object has no attribute 'find'
maserati
granturismo convertible
2017
'NoneType' object has no attribute 'find'
mazda
3
2017
'NoneType' object has no attribute 'find'
mazda
6
2017
'NoneType' object has no attribute 'find'
mercedes-benz
amg gt
2017
'NoneType' object has no attribute 'find'
mercedes-benz
b-class electric drive
2017
'NoneType' object has no attribute 'find'
mercedes-benz
cla-class
2017
'NoneType' object has no attribute 'find'
mercedes-benz
gla-class
2017
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class
2017
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class coupe
2017
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class
2017
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class coupe
2017
'NoneType' object has no attribute 'find'
mercedes-benz
gls-class
2017
'NoneType' object has no attribute 'find'
mercedes-benz
maybach
2017
'NoneType' object has no attribute 'find'
mercedes-benz
slc-class
2017
'NoneType' object has no attribute 'find'
nissan
nv cargo
2017
'NoneType' object has no attribute 'find'
nissan
nv passenger
2017
'NoneType' object has no attribute 'find'
ram
1500
2017
'NoneType' object has no attribute 'find'
ram
2500
2017
'NoneType' object has no attribute 'find'
ram
3500
2017
'NoneType' object has no attribute 'find'
rolls-royce
phantom drophead coupe
2017
'NoneType' object has no attribute 'find'
volkswagen
beetle convertible
2017
'NoneType' object has no attribute 'find'
volvo
s60 cross country
2017
'NoneType' object has no attribute 'find'
volvo
v60 cross country
2017
'NoneType' object has no attribute 'find'
volvo
v90 cross country
2017
'NoneType' object has no attribute 'find'
aston martin
rapide s
2016
'NoneType' object has no attribute 'find'
aston martin
v12 vantage s
2016
'NoneType' object has no attribute 'find'
aston martin
v8 vantage
2016
'NoneType' object has no attribute 'find'
audi
tts
2016
'NoneType' object has no attribute 'find'
bmw
3 series gran turismo
2016
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2016
'NoneType' object has no attribute 'find'
bmw
5 series gran turismo
2016
'NoneType' object has no attribute 'find'
bmw
6 series gran coupe
2016
'NoneType' object has no attribute 'find'
bmw
activehybrid 5
2016
'NoneType' object has no attribute 'find'
bmw
alpina b6 gran coupe
2016
'NoneType' object has no attribute 'find'
cadillac
ats coupe
2016
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2016
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2016
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2016
'NoneType' object has no attribute 'find'
chrysler
town and country
2016
'NoneType' object has no attribute 'find'
ferrari
california t
2016
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2016
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2016
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2016
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2016
'NoneType' object has no attribute 'find'
ford
shelby gt350
2016
'NoneType' object has no attribute 'find'
ford
transit van
2016
'NoneType' object has no attribute 'find'
ford
transit wagon
2016
'NoneType' object has no attribute 'find'
gmc
savana cargo
2016
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2016
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2016
'NoneType' object has no attribute 'find'
jaguar
xj-series
2016
'NoneType' object has no attribute 'find'
maserati
granturismo convertible
2016
'NoneType' object has no attribute 'find'
mazda
3
2016
'NoneType' object has no attribute 'find'
mazda
6
2016
'NoneType' object has no attribute 'find'
mclaren
675lt coupe
2016
'NoneType' object has no attribute 'find'
mclaren
675lt spider
2016
'NoneType' object has no attribute 'find'
mercedes-benz
amg gt
2016
'NoneType' object has no attribute 'find'
mercedes-benz
b-class electric drive
2016
'NoneType' object has no attribute 'find'
mercedes-benz
cla-class
2016
'NoneType' object has no attribute 'find'
mercedes-benz
gla-class
2016
'NoneType' object has no attribute 'find'
mercedes-benz
glc-class
2016
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class
2016
'NoneType' object has no attribute 'find'
mercedes-benz
gle-class coupe
2016
'NoneType' object has no attribute 'find'
mercedes-benz
maybach
2016
'NoneType' object has no attribute 'find'
mercedes-benz
sprinter worker
2016
'NoneType' object has no attribute 'find'
mini
cooper clubman
2016
'NoneType' object has no attribute 'find'
mini
cooper countryman
2016
'NoneType' object has no attribute 'find'
mini
cooper paceman
2016
'NoneType' object has no attribute 'find'
nissan
nv cargo
2016
'NoneType' object has no attribute 'find'
nissan
nv passenger
2016
'NoneType' object has no attribute 'find'
ram
1500
2016
'NoneType' object has no attribute 'find'
ram
2500
2016
'NoneType' object has no attribute 'find'
ram
3500
2016
'NoneType' object has no attribute 'find'
rolls-royce
phantom coupe
2016
'NoneType' object has no attribute 'find'
rolls-royce
phantom drophead coupe
2016
'NoneType' object has no attribute 'find'
volkswagen
beetle convertible
2016
'NoneType' object has no attribute 'find'
volvo
v60 cross country
2016
'NoneType' object has no attribute 'find'
aston martin
rapide s
2015
'NoneType' object has no attribute 'find'
aston martin
v12 vantage s
2015
'NoneType' object has no attribute 'find'
aston martin
v8 vantage
2015
'NoneType' object has no attribute 'find'
audi
tts
2015
'NoneType' object has no attribute 'find'
bentley
continental gt3-r
2015
'NoneType' object has no attribute 'find'
bmw
3 series gran turismo
2015
'NoneType' object has no attribute 'find'
bmw
4 series gran coupe
2015
'NoneType' object has no attribute 'find'
bmw
5 series gran turismo
2015
'NoneType' object has no attribute 'find'
bmw
6 series gran coupe
2015
'NoneType' object has no attribute 'find'
bmw
activehybrid 5
2015
'NoneType' object has no attribute 'find'
bmw
activehybrid 7
2015
'NoneType' object has no attribute 'find'
bmw
alpina b6 gran coupe
2015
'NoneType' object has no attribute 'find'
cadillac
ats coupe
2015
'NoneType' object has no attribute 'find'
cadillac
cts-v coupe
2015
'NoneType' object has no attribute 'find'
chevrolet
express cargo
2015
'NoneType' object has no attribute 'find'
chevrolet
silverado 2500hd
2015
'NoneType' object has no attribute 'find'
chevrolet
silverado 3500hd
2015
'NoneType' object has no attribute 'find'
chrysler
town and country
2015
'NoneType' object has no attribute 'find'
ferrari
california t
2015
'NoneType' object has no attribute 'find'
ford
f-250 super duty
2015
'NoneType' object has no attribute 'find'
ford
f-350 super duty
2015
'NoneType' object has no attribute 'find'
ford
f-450 super duty
2015
'NoneType' object has no attribute 'find'
ford
fusion hybrid
2015
'NoneType' object has no attribute 'find'
ford
shelby gt350
2015
'NoneType' object has no attribute 'find'
ford
transit van
2015
'NoneType' object has no attribute 'find'
ford
transit wagon
2015
'NoneType' object has no attribute 'find'
gmc
savana cargo
2015
'NoneType' object has no attribute 'find'
gmc
sierra 2500hd
2015
'NoneType' object has no attribute 'find'
gmc
sierra 3500hd
2015
'NoneType' object has no attribute 'find'
infiniti
q60 convertible
2015
'NoneType' object has no attribute 'find'
infiniti
q60 coupe
2015
'NoneType' object has no attribute 'find'
jaguar
xj-series
2015
'NoneType' object has no attribute 'find'
jaguar
xk-series
2015
'NoneType' object has no attribute 'find'
maserati
granturismo convertible
2015
'NoneType' object has no attribute 'find'
mazda
3
2015
'NoneType' object has no attribute 'find'
mazda
5
2015
'NoneType' object has no attribute 'find'
mazda
6
2015
'NoneType' object has no attribute 'find'
mclaren
650s coupe
2015
'NoneType' object has no attribute 'find'
mclaren
650s spider
2015
'NoneType' object has no attribute 'find'
mercedes-benz
b-class electric drive
2015
'NoneType' object has no attribute 'find'
mercedes-benz
sls amg gt final edition
2015
'NoneType' object has no attribute 'find'
mini
cooper countryman
2015
'NoneType' object has no attribute 'find'
mini
cooper coupe
2015
'NoneType' object has no attribute 'find'
mini
cooper paceman
2015
'NoneType' object has no attribute 'find'
mini
cooper roadster
2015
'NoneType' object has no attribute 'find'
nissan
nv cargo
2015
'NoneType' object has no attribute 'find'
nissan
nv passenger
2015
'NoneType' object has no attribute 'find'
nissan
versa note
2015
'NoneType' object has no attribute 'find'
ram
1500
2015

In [5]:
results = pd.DataFrame(car_prices)
results.to_csv("carapi-fair-prices.csv")

In [6]:
results

       make              model  year  min_price  median_price
0     acura                ilx  2020      19995         23569
1     acura                mdx  2020      22458         27193
2     acura                nsx  2020     144475        144475
3     acura                rdx  2020      23704         27402
4     acura                rlx  2020      32142         32142
...     ...                ...   ...        ...           ...
2178  volvo                s80  2015       8911         10179
2179  volvo                v60  2015       8932         11201
2180  volvo  v60 cross country  2015          0             0
2181  volvo               xc60  2015       7181         11014
2182  volvo               xc70  2015      11023         14353

[2183 rows x 5 columns]

In [8]:
carapi = carapi.rename(columns={"Make Id": "make_id", "Make Name": "make", "Model Id": "model_id", "Model Name": "model", "Trim Id": "trim_id", "Trim Year": "year", "Trim Name": "trim"})
carapi

,make_id,make,model_id,model,trim_id,year,trim,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Epa Highway Mpg,Mileage Range City,Mileage Range Highway,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric
0,1,Acura,97,ILX,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,Acura,97,ILX,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,Acura,97,ILX,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,Acura,97,ILX,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,Acura,97,ILX,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,34.0,3168.0,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,Volvo,589,XC70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,25.0,3330.0,4625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17658,23,Volvo,589,XC70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,31.0,4440.0,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17659,23,Volvo,589,XC70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,31.0,4440.0,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17660,23,Volvo,589,XC70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,24.0,3145.0,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17661,23,Volvo,589,XC70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,24.0,3145.0,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
carapi["make"] = carapi["make"].str.lower()
carapi["model"] = carapi["model"].str.lower()

In [21]:
combined_dataset = pd.merge(carapi, results, on=["make", "model", "year"], how="left")
combined_dataset.to_csv("combined.csv", index=False)

In [27]:
combined_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17662 entries, 0 to 17661
Data columns (total 59 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   make_id                                      17662 non-null  int64
 1   make                                         17662 non-null  object
 2   model_id                                     17662 non-null  int64
 3   model                                        17662 non-null  object
 4   trim_id                                      17662 non-null  int64
 5   year                                         17662 non-null  int64
 6   trim                                         17662 non-null  object
 7   Trim Description                             17662 non-null  object
 8   Trim Msrp                                    17662 non-null  int64
 9   Trim Invoice                                 17662 non-null  int64
 10  Trim Created                                 17662 non-null  object
 11  Trim Modified                                17662 non-null  object
 12  Engine Id                                    17662 non-null  int64
 13  Engine Type                                  17662 non-null  object
 14  Engine Fuel Type                             17574 non-null  object
 15  Engine Cylinders                             17441 non-null  object
 16  Engine Size                                  17441 non-null  float64
 17  Engine Horsepower Hp                         17520 non-null  float64
 18  Engine Horsepower Rpm                        17136 non-null  float64
 19  Engine Torque Ft Lbs                         17181 non-null  float64
 20  Engine Torque Rpm                            16863 non-null  float64
 21  Engine Valves                                17441 non-null  float64
 22  Engine Valve Timing                          16338 non-null  object
 23  Engine Cam Type                              17441 non-null  object
 24  Engine Drive Type                            17662 non-null  object
 25  Engine Transmission                          17662 non-null  object
 26  Body Id                                      17662 non-null  int64
 27  Body Type                                    17662 non-null  object
 28  Body Doors                                   17662 non-null  int64
 29  Body Seats                                   17662 non-null  int64
 30  Body Length                                  17551 non-null  float64
 31  Body Width                                   16784 non-null  float64
 32  Body Height                                  17397 non-null  float64
 33  Body Wheel Base                              17563 non-null  float64
 34  Body Front Track                             338 non-null    float64
 35  Body Rear Track                              338 non-null    float64
 36  Body Ground Clearance                        11560 non-null  float64
 37  Body Cargo Capacity                          12670 non-null  float64
 38  Body Max Cargo Capacity                      8794 non-null   float64
 39  Body Curb Weight                             15715 non-null  float64
 40  Body Gross Weight                            10830 non-null  float64
 41  Body Max Payload                             9146 non-null   float64
 42  Body Max Towing Capacity                     9447 non-null   float64
 43  Mileage Id                                   17662 non-null  int64
 44  Mileage Fuel Tank Capacity                   17125 non-null  float64
 45  Mileage Combined Mpg                         14623 non-null  float64
 46  Mileage Epa City Mpg                         14558 non-null  float64
 47  Mileage Epa Highway Mpg                      14558 non-null  float64
 48  Mileage Range City                           17441 non-null  float64
 49  Mileage Range Highway                        17441 non-null  float64
 50  Mileage Epa Combined Mpg Electric            461 non-null    float64
 51  Mileage Epa City Mpg Electric                388 non-null    float64
 52  Mileage Epa Highway Mpg Electric             388 non-null    float64
 53  Mileage Range Electric                       324 non-null    float64
 54  Mileage Epa Kwh 100 Mi Electric              298 non-null    float64
 55  Mileage Epa Time To Charge Hr 240v Electric  315 non-null    float64
 56  Mileage Battery Capacity Electric            161 non-null    float64
 57  min_price                                    17662 non-null  int64
 58  median_price                                 17662 non-null  int64
dtypes: float64(32), int64(13), object(14)
memory usage: 8.0+ MB

In [28]:
combined_dataset["Engine Drive Type"].value_counts()

Engine Drive Type
rear wheel drive     5165
front wheel drive    4917
all wheel drive      4416
four wheel drive     3164
Name: count, dtype: int64

------------------

In [26]:
safety = pd.read_csv("safercar_data.csv")
safety = safety.rename(columns={"MAKE": "make", "MODEL": "model", "MODEL_YR": "year"})
safety["make"] = safety["make"].str.lower()
safety["model"] = safety["model"].str.lower()
safety

/var/folders/h8/bfd5s_0922dbdzrpwd6d93sr0000gn/T/ipykernel_80707/2772499958.py:1: DtypeWarning: Columns (22,36,39,42,43,52,55,58,61,72,73,75,115,123,126,127) have mixed types. Specify dtype option on import or set low_memory=False.
  safety = pd.read_csv("safercar_data.csv")

,make,model,year,BODY_STYLE,VEHICLE_TYPE,DRIVE_TRAIN,PRODUCTION_RELEASE,VEHICLE_CLASS,BODY_FRAME,NUM_OF_SEATING,...,POLE_HIC_36_DRIV,PELVIC_FORCE,ROLLOVER_POSSIBILITY,STATIC_STABI_FACTOR,TIP,ROLL_SAFETY_CONCERN,ROLL_FOOT_NOTES,ROLLOVER_STARS,NHTSA_BACKUP_CAMERA,BACKUP_CAMERA
0,acura,adx,2025,SUV,MPV,AWD,1,NaN,,5,...,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN
1,acura,adx,2025,SUV,MPV,FWD,1,NaN,,5,...,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN
2,acura,integra,2025,5 HB,PC,FWD,1,NaN,,5,...,235.989,2871.970,0.095,1.480,No Tip,NaN,NaN,5.0,NaN,NaN
3,acura,integra type-s,2025,5 HB,PC,FWD,1,NaN,,4,...,NaN,NaN,0.095,1.480,No Tip,NaN,NaN,5.0,NaN,NaN
4,acura,mdx,2025,SUV,MPV,AWD,1,NaN,,7,...,549.430,1886.689,0.151,NaN,No Tip,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11731,volvo,xc60,2011,SUV,MPV,FWD,1,SUV,Uni-Body,5,...,242.120,3207.978,0.176,1.216,No Tip,NaN,NaN,4.0,NaN,NaN
11732,volvo,xc70,2011,SW,MPV,AWD,1,SUV,Uni-Body,5,...,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN
11733,volvo,xc70,2011,SW,MPV,FWD,1,SUV,Uni-Body,5,...,NaN,NaN,0.000,0.000,NaN,NaN,NaN,NaN,NaN,NaN
11734,volvo,xc90,2011,SUV,MPV,AWD,1,SUV,Uni-Body,7,...,NaN,NaN,0.179,1.210,No Tip,NaN,NaN,4.0,NaN,NaN
11735,volvo,xc90,2011,SUV,MPV,FWD,1,SUV,Uni-Body,7,...,NaN,NaN,0.191,1.190,No Tip,NaN,NaN,4.0,NaN,NaN

In [29]:
safety["DRIVE_TRAIN"].value_counts()

DRIVE_TRAIN
AWD     4073
RWD     2941
FWD     2740
4WD     1348
2WD      368
4x2      130
4x4      129
AWD        3
           1
ADW        1
fWD        1
Name: count, dtype: int64

In [32]:
combined_dataset = combined_dataset.rename(columns={"Engine Drive Type": "drive_train"})
safety = safety.rename(columns={"DRIVE_TRAIN": "drive_train"})

In [37]:
safety = safety.rename(columns={"OVERALL_STARS": "accident_safety_rating"})

In [33]:
def drivetrain(row):
    if row["drive_train"] == "rear wheel drive":
        return "RWD"
    elif row["drive_train"] == "front wheel drive":
        return "FWD"
    elif row["drive_train"] == "all wheel drive":
        return "AWD"
    else:
        return "4WD"

combined_dataset["drive_train"] = combined_dataset.apply(drivetrain, axis=1)

In [34]:
combined_dataset.drive_train.value_counts()

drive_train
RWD    5165
FWD    4917
AWD    4416
4WD    3164
Name: count, dtype: int64

In [41]:
combined_dataset

,make_id,make,model_id,model,trim_id,year,trim,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Range Highway,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric,min_price,median_price
0,1,acura,97,ilx,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569
1,1,acura,97,ilx,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569
2,1,acura,97,ilx,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569
3,1,acura,97,ilx,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569
4,1,acura,97,ilx,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,4488.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,volvo,589,xc70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,4625.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353
17658,23,volvo,589,xc70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353
17659,23,volvo,589,xc70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,5735.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353
17660,23,volvo,589,xc70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353
17661,23,volvo,589,xc70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,4440.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353

In [38]:
safety = safety[["make", "model", "year", "drive_train", "accident_safety_rating"]]

In [42]:
safety

        make           model  year drive_train  accident_safety_rating
0      acura             adx  2025         AWD                     NaN
1      acura             adx  2025         FWD                     NaN
2      acura         integra  2025         FWD                     5.0
3      acura  integra type-s  2025         FWD                     NaN
4      acura             mdx  2025         AWD                     NaN
...      ...             ...   ...         ...                     ...
11731  volvo            xc60  2011         FWD                     5.0
11732  volvo            xc70  2011         AWD                     NaN
11733  volvo            xc70  2011         FWD                     NaN
11734  volvo            xc90  2011         AWD                     NaN
11735  volvo            xc90  2011         FWD                     NaN

[11736 rows x 5 columns]

In [66]:
safety_unique = safety.drop_duplicates(subset=["make", "model", "year", "drive_train"])

In [67]:
safety_combined_dataset = pd.merge(combined_dataset, safety_unique, on=["make", "model", "year", "drive_train"], how="left")

In [68]:
safety_combined_dataset.accident_safety_rating.value_counts()

accident_safety_rating
5.0    5199
4.0    2053
Name: count, dtype: int64

In [56]:
safety_combined_dataset

,make_id,make,model_id,model,trim_id,year,trim,Trim Description,Trim Msrp,Trim Invoice,...,Mileage Epa Combined Mpg Electric,Mileage Epa City Mpg Electric,Mileage Epa Highway Mpg Electric,Mileage Range Electric,Mileage Epa Kwh 100 Mi Electric,Mileage Epa Time To Charge Hr 240v Electric,Mileage Battery Capacity Electric,min_price,median_price,accident_safety_rating
0,1,acura,97,ilx,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
1,1,acura,97,ilx,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
2,1,acura,97,ilx,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
3,1,acura,97,ilx,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
4,1,acura,97,ilx,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,volvo,589,xc70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17658,23,volvo,589,xc70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17659,23,volvo,589,xc70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17660,23,volvo,589,xc70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17661,23,volvo,589,xc70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN

In [57]:
safety_combined_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17662 entries, 0 to 17661
Data columns (total 60 columns):
 #   Column                                       Non-Null Count  Dtype
---  ------                                       --------------  -----
 0   make_id                                      17662 non-null  int64
 1   make                                         17662 non-null  object
 2   model_id                                     17662 non-null  int64
 3   model                                        17662 non-null  object
 4   trim_id                                      17662 non-null  int64
 5   year                                         17662 non-null  int64
 6   trim                                         17662 non-null  object
 7   Trim Description                             17662 non-null  object
 8   Trim Msrp                                    17662 non-null  int64
 9   Trim Invoice                                 17662 non-null  int64
 10  Trim Created                                 17662 non-null  object
 11  Trim Modified                                17662 non-null  object
 12  Engine Id                                    17662 non-null  int64
 13  Engine Type                                  17662 non-null  object
 14  Engine Fuel Type                             17574 non-null  object
 15  Engine Cylinders                             17441 non-null  object
 16  Engine Size                                  17441 non-null  float64
 17  Engine Horsepower Hp                         17520 non-null  float64
 18  Engine Horsepower Rpm                        17136 non-null  float64
 19  Engine Torque Ft Lbs                         17181 non-null  float64
 20  Engine Torque Rpm                            16863 non-null  float64
 21  Engine Valves                                17441 non-null  float64
 22  Engine Valve Timing                          16338 non-null  object
 23  Engine Cam Type                              17441 non-null  object
 24  drive_train                                  17662 non-null  object
 25  Engine Transmission                          17662 non-null  object
 26  Body Id                                      17662 non-null  int64
 27  Body Type                                    17662 non-null  object
 28  Body Doors                                   17662 non-null  int64
 29  Body Seats                                   17662 non-null  int64
 30  Body Length                                  17551 non-null  float64
 31  Body Width                                   16784 non-null  float64
 32  Body Height                                  17397 non-null  float64
 33  Body Wheel Base                              17563 non-null  float64
 34  Body Front Track                             338 non-null    float64
 35  Body Rear Track                              338 non-null    float64
 36  Body Ground Clearance                        11560 non-null  float64
 37  Body Cargo Capacity                          12670 non-null  float64
 38  Body Max Cargo Capacity                      8794 non-null   float64
 39  Body Curb Weight                             15715 non-null  float64
 40  Body Gross Weight                            10830 non-null  float64
 41  Body Max Payload                             9146 non-null   float64
 42  Body Max Towing Capacity                     9447 non-null   float64
 43  Mileage Id                                   17662 non-null  int64
 44  Mileage Fuel Tank Capacity                   17125 non-null  float64
 45  Mileage Combined Mpg                         14623 non-null  float64
 46  Mileage Epa City Mpg                         14558 non-null  float64
 47  Mileage Epa Highway Mpg                      14558 non-null  float64
 48  Mileage Range City                           17441 non-null  float64
 49  Mileage Range Highway                        17441 non-null  float64
 50  Mileage Epa Combined Mpg Electric            461 non-null    float64
 51  Mileage Epa City Mpg Electric                388 non-null    float64
 52  Mileage Epa Highway Mpg Electric             388 non-null    float64
 53  Mileage Range Electric                       324 non-null    float64
 54  Mileage Epa Kwh 100 Mi Electric              298 non-null    float64
 55  Mileage Epa Time To Charge Hr 240v Electric  315 non-null    float64
 56  Mileage Battery Capacity Electric            161 non-null    float64
 57  min_price                                    17662 non-null  int64
 58  median_price                                 17662 non-null  int64
 59  accident_safety_rating                       7252 non-null   float64
dtypes: float64(33), int64(13), object(14)
memory usage: 8.1+ MB

In [58]:
safety_combined_dataset.columns = safety_combined_dataset.columns.str.lower().str.replace(' ', '_')
safety_combined_dataset

,make_id,make,model_id,model,trim_id,year,trim,trim_description,trim_msrp,trim_invoice,...,mileage_epa_combined_mpg_electric,mileage_epa_city_mpg_electric,mileage_epa_highway_mpg_electric,mileage_range_electric,mileage_epa_kwh_100_mi_electric,mileage_epa_time_to_charge_hr_240v_electric,mileage_battery_capacity_electric,min_price,median_price,accident_safety_rating
0,1,acura,97,ilx,6292,2020,Base,4dr Sedan (2.4L 4cyl 8AM),25900,24617,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
1,1,acura,97,ilx,6295,2020,Premium and A-SPEC Packages,Premium and A-SPEC Packages 4dr Sedan (2.4L 4c...,29750,28264,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
2,1,acura,97,ilx,6293,2020,Premium Package,Premium Package 4dr Sedan (2.4L 4cyl 8AM),27750,26370,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
3,1,acura,97,ilx,6296,2020,Technology and A-SPEC Packages,Technology and A-SPEC Packages 4dr Sedan (2.4L...,31650,30064,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
4,1,acura,97,ilx,6294,2020,Technology Package,Technology Package 4dr Sedan (2.4L 4cyl 8AM),29650,28169,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19995,23569,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17657,23,volvo,589,xc70,23952,2015,3.2,3.2 4dr Wagon AWD (3.2L 6cyl 6A),37550,35297,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17658,23,volvo,589,xc70,23949,2015,T5 Drive-E,T5 Drive-E 4dr Wagon w/Prod. End 5/14 (2.0L 4c...,35400,33276,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17659,23,volvo,589,xc70,23950,2015,T5 Drive-E,T5 Drive-E 4dr Wagon (2.0L 4cyl Turbo 8A),36050,33887,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17660,23,volvo,589,xc70,23954,2015,T6,T6 4dr Wagon AWD (3.0L 6cyl Turbo 6A),42050,39527,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN
17661,23,volvo,589,xc70,23953,2015,T6,T6 4dr Wagon AWD w/Prod. End 5/14 (3.0L 6cyl T...,41800,39292,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11023,14353,NaN

In [60]:
safety_combined_dataset.to_csv("safety_combined_dataset.csv", index=False)

In [62]:
safety_unique["accident_safety_rating"].value_counts()

accident_safety_rating
5.0    2907
4.0    1446
3.0      94
2.0      18
Name: count, dtype: int64